# Generated by Django 2.0.7 on 2018-07-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rut'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'Doctor'), ('2', 'Paciente')], default='Paciente', max_length=255, verbose_name='Tipo de usuario'),
        ),
    ]
