# Generated by Django 2.0.7 on 2018-07-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180714_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'Medico'), ('2', 'Paciente')], default='Paciente', max_length=255, verbose_name='Tipo de usuario'),
        ),
    ]
