# Generated by Django 2.0.7 on 2018-07-14 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=255, verbose_name='codigo examen')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre examen')),
                ('description', models.TextField(blank=True, verbose_name='Descripción examen')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('observations', models.TextField(blank=True, verbose_name='observaciones')),
                ('exams', models.ManyToManyField(blank=True, to='medrecords_app.Exam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('fantasy_name', models.CharField(blank=True, max_length=255, verbose_name='NOmbre de fantasia')),
                ('type_medicine', models.CharField(blank=True, choices=[('', ''), ('1', 'Analgésico'), ('2', 'Antidepresivos'), ('3', 'Hormonas'), ('4', 'Antibioticos')], max_length=255, verbose_name='tipo de medicina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='medicines',
            field=models.ManyToManyField(blank=True, to='medrecords_app.Medicine'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
