# Generated by Django 2.0.7 on 2018-07-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medrecords_app', '0002_auto_20180715_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='type_medicine',
            field=models.CharField(blank=True, choices=[('', ''), (1, 'Analgésico'), (2, 'Antidepresivos'), (3, 'Hormonas'), (4, 'Antibioticos')], max_length=255, verbose_name='tipo de medicina'),
        ),
    ]
